CREATE TYPE "TipoIngrediente" AS ENUM (
  'macro',
  'micro'
);

CREATE TYPE "Contenido" AS ENUM (
  'funda',
  'gr',
  'kg',
  'lb',
  'saco',
  'granel',
  'bazuca',
  'tonelada'
);

CREATE TYPE "PhoneType" AS ENUM (
  'casa',
  'oficina',
  'celular'
);

CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "password" char(64) NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Empresa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "contactos" int,
  "direccion" varchar(255) NOT NULL,
  "provincia" varchar(50) NOT NULL,
  "email" varchar(255),
  "geoposicion" int,
  "areas" int,
  "owner" int NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Telefono" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero" varchar(50) NOT NULL,
  "tipo" "PhoneType" DEFAULT 'oficina',
  "owner" int NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Geoposicion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lat" float8,
  "lon" float8,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Area" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" text NOT NULL,
  "capacidad" int8,
  "largo" float8,
  "ancho" float8,
  "tipo_area" int NOT NULL,
  "equipos" int NOT NULL,
  "owner" int NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "AreaType" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "owner" int NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Equipo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "marca" varchar(20) NOT NULL,
  "modelo" varchar(20) NOT NULL,
  "serie" varchar(50) NOT NULL,
  "descripcion" text NOT NULL,
  "tipo" int NOT NULL,
  "componentes" int NOT NULL,
  "owner" int NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "EquipoType" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "owner" int NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Componente" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "marca" varchar(20) NOT NULL,
  "modelo" varchar(20) NOT NULL,
  "serie" varchar(50) NOT NULL,
  "descripcion" text NOT NULL,
  "vida_util" int8 DEFAULT 0,
  "tipo" int NOT NULL,
  "owner" int NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "ComponenteType" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "owner" int NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Alimento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "macros" int NOT NULL,
  "micros" int NOT NULL,
  "precio" int8 NOT NULL,
  "owner" int NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Ingrediente" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "descripcion" text NOT NULL,
  "ficha_tecnica" text NOT NULL,
  "cantidad" int8 NOT NULL,
  "unidad" "Contenido" DEFAULT 'lb',
  "precio" int8 NOT NULL,
  "tipo" "TipoIngrediente" DEFAULT 'macro',
  "suplidor" int NOT NULL,
  "owner" int NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Suplidor" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "direccion" varchar(255) NOT NULL,
  "contactos" int NOT NULL,
  "owner" int NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE INDEX ON "User" ("email");

CREATE INDEX ON "User" ("nombre");

CREATE INDEX ON "Empresa" ("nombre");

CREATE INDEX ON "Empresa" ("provincia");

CREATE INDEX ON "Empresa" ("direccion");

CREATE INDEX ON "Telefono" ("numero");

CREATE INDEX ON "Area" ("tipo_area");

CREATE INDEX ON "AreaType" ("nombre");

CREATE INDEX ON "Equipo" ("marca");

CREATE INDEX ON "Equipo" ("modelo");

CREATE INDEX ON "Equipo" ("serie");

CREATE INDEX ON "EquipoType" ("nombre");

CREATE INDEX ON "Componente" ("marca");

CREATE INDEX ON "Componente" ("modelo");

CREATE INDEX ON "Componente" ("serie");

CREATE INDEX ON "ComponenteType" ("nombre");

CREATE INDEX ON "Alimento" ("nombre");

CREATE INDEX ON "Suplidor" ("nombre");

ALTER TABLE "Telefono" ADD FOREIGN KEY ("id") REFERENCES "Empresa" ("contactos");

ALTER TABLE "Empresa" ADD FOREIGN KEY ("geoposicion") REFERENCES "Geoposicion" ("id");

ALTER TABLE "Area" ADD FOREIGN KEY ("id") REFERENCES "Empresa" ("areas");

ALTER TABLE "Empresa" ADD FOREIGN KEY ("owner") REFERENCES "User" ("id");

ALTER TABLE "Telefono" ADD FOREIGN KEY ("owner") REFERENCES "User" ("id");

ALTER TABLE "Area" ADD FOREIGN KEY ("tipo_area") REFERENCES "AreaType" ("id");

ALTER TABLE "Equipo" ADD FOREIGN KEY ("id") REFERENCES "Area" ("equipos");

ALTER TABLE "Area" ADD FOREIGN KEY ("owner") REFERENCES "User" ("id");

ALTER TABLE "AreaType" ADD FOREIGN KEY ("owner") REFERENCES "User" ("id");

ALTER TABLE "Equipo" ADD FOREIGN KEY ("tipo") REFERENCES "EquipoType" ("id");

ALTER TABLE "Componente" ADD FOREIGN KEY ("id") REFERENCES "Equipo" ("componentes");

ALTER TABLE "Equipo" ADD FOREIGN KEY ("owner") REFERENCES "User" ("id");

ALTER TABLE "EquipoType" ADD FOREIGN KEY ("owner") REFERENCES "User" ("id");

ALTER TABLE "Componente" ADD FOREIGN KEY ("tipo") REFERENCES "ComponenteType" ("id");

ALTER TABLE "Componente" ADD FOREIGN KEY ("owner") REFERENCES "User" ("id");

ALTER TABLE "ComponenteType" ADD FOREIGN KEY ("owner") REFERENCES "User" ("id");

ALTER TABLE "Ingrediente" ADD FOREIGN KEY ("id") REFERENCES "Alimento" ("macros");

ALTER TABLE "Ingrediente" ADD FOREIGN KEY ("id") REFERENCES "Alimento" ("micros");

ALTER TABLE "Alimento" ADD FOREIGN KEY ("owner") REFERENCES "User" ("id");

ALTER TABLE "Ingrediente" ADD FOREIGN KEY ("suplidor") REFERENCES "Suplidor" ("id");

ALTER TABLE "Ingrediente" ADD FOREIGN KEY ("owner") REFERENCES "User" ("id");

ALTER TABLE "Telefono" ADD FOREIGN KEY ("id") REFERENCES "Suplidor" ("contactos");

ALTER TABLE "Suplidor" ADD FOREIGN KEY ("owner") REFERENCES "User" ("id");

ALTER TABLE "Ingrediente" ADD FOREIGN KEY ("nombre") REFERENCES "Ingrediente" ("cantidad");
